# Generated by Django 2.2.24 on 2021-12-02 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurer', models.CharField(max_length=255)),
                ('number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Number')),
                ('end_date', models.DateField(blank=True, help_text='If provided, will apply to all policies in the contract.', null=True, verbose_name='End Date')),
                ('cancellation_date', models.DateField(blank=True, null=True, verbose_name='Cancellation Date')),
                ('publish_date', models.DateField(blank=True, null=True, verbose_name='Publish Date')),
                ('effective_date', models.DateField(blank=True, null=True, verbose_name='Effective Date')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Payment Date')),
            ],
        ),
    ]
